# Generated by Django 6.0.3 on 2026-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(help_text='e.g. Founder & CEO', max_length=150)),
                ('photo', models.ImageField(upload_to='ceo/')),
                ('short_bio', models.TextField(help_text='Shown on the homepage — keep this brief, 2-3 sentences')),
                ('full_bio', models.TextField(help_text="Shown on the full 'Meet the CEO' page — can be as long as you like")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
